import "./globals.css";
import Nav from "./components/common-components/Nav";
import { Righteous } from "next/font/google";
import AOSWrapper from "./components/common-components/AOSWrapper";

const righteous = Righteous({
  variable: "--font-righteous",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${righteous.variable} antialiased`}>
        <AOSWrapper>
          <Nav />
          {children}
        </AOSWrapper>
      </body>
    </html>
  );
}
