import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/(common)/Nav";
import Footer from "./components/(common)/Footer";
import Breadcrumb from "./components/(common)/Breadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/portfolio-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700;800&family=Comfortaa:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        <Breadcrumb />
        {children}
        <Footer />
      </body>
    </html>
  );
}
